include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - avoid_print
    - camel_case_types
    - library_private_types_in_public_api
