name: food_recognizer
description: "Aplikasi Pintar Pendeteksi Makanan, Analisis Nutrisi Gizi, Verifikasi Kehalalan & Resep Tradisional Berbasis Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  camera: ^0.11.0+2
  google_generative_ai: ^0.4.0
  flutter_tts: ^4.1.0
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt
